[build]
nixpkgs = ["libGL", "libglib"]

[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0"]

[phases.build]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn app:app"
